{{- $fullname := include "rollout-ecr-tagger.fullname" . -}}
{{- $sa := include "rollout-ecr-tagger.serviceAccountName" . -}}
{{- if empty .Values.watchNamespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "rollout-ecr-tagger.labels" . | nindent 4 }}
rules:
  {{- include "rollout-ecr-tagger.workloadRules" . | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "rollout-ecr-tagger.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $fullname }}
subjects:
- kind: ServiceAccount
  name: {{ $sa }}
  namespace: {{ .Release.Namespace }}
{{- else }}
{{- range .Values.watchNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $fullname }}
  namespace: {{ . }}
  labels:
    {{- include "rollout-ecr-tagger.labels" $ | nindent 4 }}
rules:
  {{- include "rollout-ecr-tagger.workloadRules" $ | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $fullname }}
  namespace: {{ . }}
  labels:
    {{- include "rollout-ecr-tagger.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $fullname }}
subjects:
- kind: ServiceAccount
  name: {{ $sa }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}
{{- if .Values.leaderElection }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $fullname }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rollout-ecr-tagger.labels" . | nindent 4 }}
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $fullname }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rollout-ecr-tagger.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $fullname }}-leader-election
subjects:
- kind: ServiceAccount
  name: {{ $sa }}
  namespace: {{ .Release.Namespace }}
{{- end }}
