apiVersion: v2
name: rollout-ecr-tagger
description: Retags images in Amazon ECR when Argo Rollouts (and optionally Deployments) finish rolling out.
type: application
version: 0.5.0
appVersion: "v0.5.0"
home: https://github.com/henryd24/kubernetes-operator-tag-images
sources:
  - https://github.com/henryd24/kubernetes-operator-tag-images
keywords:
  - ecr
  - argo-rollouts
  - operator
